/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package control.work;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Data extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3548419581320637222L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Data\",\"namespace\":\"control.work\",\"fields\":[{\"name\":\"num\",\"type\":\"int\"},{\"name\":\"code\",\"type\":\"int\"},{\"name\":\"someString\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Data> ENCODER =
      new BinaryMessageEncoder<Data>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Data> DECODER =
      new BinaryMessageDecoder<Data>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Data> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Data> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Data> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Data>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Data to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Data from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Data instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Data fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int num;
  private int code;
  private java.lang.CharSequence someString;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Data() {}

  /**
   * All-args constructor.
   * @param num The new value for num
   * @param code The new value for code
   * @param someString The new value for someString
   */
  public Data(java.lang.Integer num, java.lang.Integer code, java.lang.CharSequence someString) {
    this.num = num;
    this.code = code;
    this.someString = someString;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return num;
    case 1: return code;
    case 2: return someString;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: num = (java.lang.Integer)value$; break;
    case 1: code = (java.lang.Integer)value$; break;
    case 2: someString = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'num' field.
   * @return The value of the 'num' field.
   */
  public int getNum() {
    return num;
  }


  /**
   * Sets the value of the 'num' field.
   * @param value the value to set.
   */
  public void setNum(int value) {
    this.num = value;
  }

  /**
   * Gets the value of the 'code' field.
   * @return The value of the 'code' field.
   */
  public int getCode() {
    return code;
  }


  /**
   * Sets the value of the 'code' field.
   * @param value the value to set.
   */
  public void setCode(int value) {
    this.code = value;
  }

  /**
   * Gets the value of the 'someString' field.
   * @return The value of the 'someString' field.
   */
  public java.lang.CharSequence getSomeString() {
    return someString;
  }


  /**
   * Sets the value of the 'someString' field.
   * @param value the value to set.
   */
  public void setSomeString(java.lang.CharSequence value) {
    this.someString = value;
  }

  /**
   * Creates a new Data RecordBuilder.
   * @return A new Data RecordBuilder
   */
  public static control.work.Data.Builder newBuilder() {
    return new control.work.Data.Builder();
  }

  /**
   * Creates a new Data RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Data RecordBuilder
   */
  public static control.work.Data.Builder newBuilder(control.work.Data.Builder other) {
    if (other == null) {
      return new control.work.Data.Builder();
    } else {
      return new control.work.Data.Builder(other);
    }
  }

  /**
   * Creates a new Data RecordBuilder by copying an existing Data instance.
   * @param other The existing instance to copy.
   * @return A new Data RecordBuilder
   */
  public static control.work.Data.Builder newBuilder(control.work.Data other) {
    if (other == null) {
      return new control.work.Data.Builder();
    } else {
      return new control.work.Data.Builder(other);
    }
  }

  /**
   * RecordBuilder for Data instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Data>
    implements org.apache.avro.data.RecordBuilder<Data> {

    private int num;
    private int code;
    private java.lang.CharSequence someString;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(control.work.Data.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.num)) {
        this.num = data().deepCopy(fields()[0].schema(), other.num);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.code)) {
        this.code = data().deepCopy(fields()[1].schema(), other.code);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.someString)) {
        this.someString = data().deepCopy(fields()[2].schema(), other.someString);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Data instance
     * @param other The existing instance to copy.
     */
    private Builder(control.work.Data other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.num)) {
        this.num = data().deepCopy(fields()[0].schema(), other.num);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.code)) {
        this.code = data().deepCopy(fields()[1].schema(), other.code);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.someString)) {
        this.someString = data().deepCopy(fields()[2].schema(), other.someString);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'num' field.
      * @return The value.
      */
    public int getNum() {
      return num;
    }


    /**
      * Sets the value of the 'num' field.
      * @param value The value of 'num'.
      * @return This builder.
      */
    public control.work.Data.Builder setNum(int value) {
      validate(fields()[0], value);
      this.num = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'num' field has been set.
      * @return True if the 'num' field has been set, false otherwise.
      */
    public boolean hasNum() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'num' field.
      * @return This builder.
      */
    public control.work.Data.Builder clearNum() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'code' field.
      * @return The value.
      */
    public int getCode() {
      return code;
    }


    /**
      * Sets the value of the 'code' field.
      * @param value The value of 'code'.
      * @return This builder.
      */
    public control.work.Data.Builder setCode(int value) {
      validate(fields()[1], value);
      this.code = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'code' field has been set.
      * @return True if the 'code' field has been set, false otherwise.
      */
    public boolean hasCode() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'code' field.
      * @return This builder.
      */
    public control.work.Data.Builder clearCode() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'someString' field.
      * @return The value.
      */
    public java.lang.CharSequence getSomeString() {
      return someString;
    }


    /**
      * Sets the value of the 'someString' field.
      * @param value The value of 'someString'.
      * @return This builder.
      */
    public control.work.Data.Builder setSomeString(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.someString = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'someString' field has been set.
      * @return True if the 'someString' field has been set, false otherwise.
      */
    public boolean hasSomeString() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'someString' field.
      * @return This builder.
      */
    public control.work.Data.Builder clearSomeString() {
      someString = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Data build() {
      try {
        Data record = new Data();
        record.num = fieldSetFlags()[0] ? this.num : (java.lang.Integer) defaultValue(fields()[0]);
        record.code = fieldSetFlags()[1] ? this.code : (java.lang.Integer) defaultValue(fields()[1]);
        record.someString = fieldSetFlags()[2] ? this.someString : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Data>
    WRITER$ = (org.apache.avro.io.DatumWriter<Data>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Data>
    READER$ = (org.apache.avro.io.DatumReader<Data>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.num);

    out.writeInt(this.code);

    out.writeString(this.someString);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.num = in.readInt();

      this.code = in.readInt();

      this.someString = in.readString(this.someString instanceof Utf8 ? (Utf8)this.someString : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.num = in.readInt();
          break;

        case 1:
          this.code = in.readInt();
          break;

        case 2:
          this.someString = in.readString(this.someString instanceof Utf8 ? (Utf8)this.someString : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










